// src-tauri/src/infrastructure/ai/gemini_adapter.rs
use async_trait::async_trait;
use crate::application::ports::ai::AIPort;
use crate::domain::errors::DomainError;
use reqwest::Client;
use serde_json::json;

pub struct GeminiAIAdapter {
    client: Client,
    api_key: String,
}

impl GeminiAIAdapter {
    pub fn new(api_key: String) -> Self {
        Self {
            client: Client::new(),
            api_key,
        }
    }
}

#[async_trait]
impl AIPort for GeminiAIAdapter {
    async fn generate_tests(&self, url: &str, response_body: &str) -> Result<String, DomainError> {
        if self.api_key.is_empty() || self.api_key == "MOCK_KEY" {
             // Mock behavior for demonstration if key is missing
             return Ok(format!(
"pm.test('Status code is 200', () => {{
    pm.response.to.have.status(200);
}});

pm.test('Response is valid JSON', () => {{
    pm.response.to.be.json;
}});

// Autogenerated tests for {}
pm.test('Response must be an object', () => {{
    const jsonData = pm.response.json();
    pm.expect(jsonData).to.be.an('object');
}});", url));
        }
        
        let prompt = format!(
            "Você é um especialista em testes de API. Baseado na URL: '{}' e no corpo da resposta JSON abaixo, gere scripts de teste em JavaScript para o motor Postman. Utilize a sintaxe: pm.test('descrição', () => {{ ... }});
            
            Corpo:
            {}
            
            Gere apenas o código JavaScript sem explicações, sem blocos de markdown e sem caracteres extras. Apenas o código puro.",
            url, response_body
        );

        let api_url = format!(
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={}",
            self.api_key
        );

        let body = json!({
            "contents": [{
                "parts": [{
                    "text": prompt
                }]
            }]
        });

        let resp = self.client.post(&api_url)
            .json(&body)
            .send()
            .await
            .map_err(|e| DomainError::NetworkError(e.to_string()))?;

        if !resp.status().is_success() {
            return Err(DomainError::NetworkError(format!("AI API Error: {}", resp.status())));
        }

        let json: serde_json::Value = resp.json().await.map_err(|e| DomainError::NetworkError(e.to_string()))?;
        
        let generated_text = json["candidates"][0]["content"]["parts"][0]["text"]
            .as_str()
            .map(|s| s.replace("```javascript", "").replace("```", "").trim().to_string())
            .unwrap_or("// Erro ao processar a resposta da IA".to_string());

        Ok(generated_text)
    }

    async fn explain_response(&self, response_body: &str) -> Result<String, DomainError> {
        if self.api_key.is_empty() || self.api_key == "MOCK_KEY" {
            return Ok("Configure sua API Key nas configurações para explicações reais.".to_string());
        }

        let prompt = format!("Explique de forma concisa o que esta resposta de API contém:\n\n{}", response_body);
        let api_url = format!("https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={}", self.api_key);
        
        let body = json!({ "contents": [{ "parts": [{ "text": prompt }] }] });
        let resp = self.client.post(&api_url).json(&body).send().await.map_err(|e| DomainError::NetworkError(e.to_string()))?;
        let json: serde_json::Value = resp.json().await.map_err(|e| DomainError::NetworkError(e.to_string()))?;
        
        let text = json["candidates"][0]["content"]["parts"][0]["text"].as_str().unwrap_or("...").to_string();
        Ok(text)
    }
}
