import React from 'react';
import { FileJson, FileText, Download } from 'lucide-react';
import type { LoadTestConfigDto, LoadTestProgressEventDto } from '../../types/ipc';

interface LoadTestReportProps {
  config: LoadTestConfigDto | null;
  snapshot: LoadTestProgressEventDto | null;
}

function downloadFile(fileName: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}

function formatMethod(method: LoadTestConfigDto['targetRequest']['method']): string {
  return typeof method === 'string' ? method : method.CUSTOM;
}

export function buildMarkdownReport(
  config: LoadTestConfigDto | null,
  snapshot: LoadTestProgressEventDto,
): string {
  const lines: string[] = [
    '# Tyny Pulse — Load Test Report',
    '',
    `- **Test ID:** \`${snapshot.testId}\``,
    `- **Generated:** ${new Date().toISOString()}`,
    '',
    '## Target Configuration',
    '',
    '| Parameter | Value |',
    '| :--- | :--- |',
    `| Method | ${config ? formatMethod(config.targetRequest.method) : 'n/a'} |`,
    `| URL | ${config?.targetRequest.url} |`,
    `| Virtual Users | ${config?.virtualUsers ?? 'n/a'} |`,
    `| Duration | ${config?.durationSeconds ?? 'n/a'}s |`,
    `| Ramp-up | ${config?.rampUpSeconds ?? 'n/a'}s |`,
    `| Timeout | ${config?.timeoutMs ?? 'n/a'}ms |`,
    '',
    '## Summary',
    '',
    '| Metric | Value |',
    '| :--- | :--- |',
    `| Total Requests | ${snapshot.totalRequests} |`,
    `| Successful | ${snapshot.successfulRequests} |`,
    `| Failed | ${snapshot.failedRequests} |`,
    `| Success Rate | ${((snapshot.successfulRequests / Math.max(1, snapshot.totalRequests)) * 100).toFixed(2)}% |`,
    `| Average RPS (smoothed) | ${snapshot.currentRps.toFixed(2)} req/s |`,
    `| Effective RPS | ${(snapshot.totalRequests / Math.max(0.001, snapshot.elapsedSeconds)).toFixed(2)} req/s |`,
    `| Throughput | ${(snapshot.bytesPerSecond / 1024).toFixed(2)} KiB/s |`,
    `| Elapsed | ${snapshot.elapsedSeconds.toFixed(2)}s |`,
    '',
    '## Latency Percentiles',
    '',
    '| Percentile | Latency (ms) |',
    '| :--- | :--- |',
    `| Min | ${snapshot.percentiles.minMs.toFixed(2)} |`,
    `| p50 (median) | ${snapshot.percentiles.p50Ms.toFixed(2)} |`,
    `| Mean | ${snapshot.percentiles.meanMs.toFixed(2)} |`,
    `| p90 | ${snapshot.percentiles.p90Ms.toFixed(2)} |`,
    `| p95 | ${snapshot.percentiles.p95Ms.toFixed(2)} |`,
    `| p99 | ${snapshot.percentiles.p99Ms.toFixed(2)} |`,
    `| Max | ${snapshot.percentiles.maxMs.toFixed(2)} |`,
    '',
    '## Status Code Breakdown',
    '',
    '| Status | Count |',
    '| :--- | :--- |',
    ...[...snapshot.statusCodes]
      .sort((a, b) => b.count - a.count)
      .map((entry) => `| ${entry.code === 0 ? 'transport error' : entry.code} | ${entry.count} |`),
    '',
    '---',
    '',
    'Generated by Tyny Pulse (ca.tyny.pulse).',
  ];
  return lines.join('\n');
}

export const LoadTestReport: React.FC<LoadTestReportProps> = ({ config, snapshot }) => {
  if (!snapshot || !snapshot.isFinished) return null;

  const exportJson = (): void => {
    const payload = {
      generator: 'tyny-pulse',
      appIdentifier: 'ca.tyny.pulse',
      exportedAt: new Date().toISOString(),
      config,
      summary: snapshot,
    };
    downloadFile(
      `load-test-${snapshot.testId}.json`,
      JSON.stringify(payload, null, 2),
      'application/json',
    );
  };

  const exportMarkdown = (): void => {
    downloadFile(
      `load-test-${snapshot.testId}.md`,
      buildMarkdownReport(config, snapshot),
      'text/markdown',
    );
  };

  return (
    <div className="lt-report-bar animate-fade-in">
      <div className="lt-report-info">
        <span className="lt-report-title">Execution Summary</span>
        <span className="lt-report-subtitle">
          Test {snapshot.testId.slice(0, 8)} finished in {snapshot.elapsedSeconds.toFixed(1)}s
        </span>
      </div>
      <div className="lt-report-actions">
        <button className="lt-export-btn" onClick={exportJson}>
          <FileJson size={16} />
          Export JSON
        </button>
        <button className="lt-export-btn" onClick={exportMarkdown}>
          <FileText size={16} />
          Export Markdown
        </button>
      </div>
      <Download size={14} className="lt-report-watermark" />
    </div>
  );
};
