// src-tauri/src/infrastructure/reporting/html_reporter.rs
//
// Self-contained HTML run report: inline styles only, no external assets,
// safe to open from disk or attach to CI artifacts. All dynamic strings are
// HTML-escaped before interpolation.

use crate::domain::models::{CollectionRunReport, RequestRunResult};

/// Escapes the five HTML-critical characters.
fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn status_class(result: &RequestRunResult) -> &'static str {
    if result.tests.iter().all(|test| test.passed) {
        "pass"
    } else {
        "fail"
    }
}

fn badge(passed: bool) -> &'static str {
    if passed {
        r#"<span class="badge pass">PASS</span>"#
    } else {
        r#"<span class="badge fail">FAIL</span>"#
    }
}

/// Renders a standalone HTML document for a collection run.
pub fn render_html(
    collection_name: &str,
    report: &CollectionRunReport,
    duration_ms: u64,
) -> String {
    let name = escape_html(collection_name);
    let passed_requests = report
        .results
        .iter()
        .filter(|result| result.tests.iter().all(|test| test.passed))
        .count();
    let failed_requests = report.total_requests - passed_requests;

    let mut rows = String::new();
    for result in &report.results {
        let passed = result.tests.iter().filter(|t| t.passed).count();
        let total = result.tests.len();
        let mut test_items = String::new();
        for test in &result.tests {
            test_items.push_str(&format!(
                "<li>{} {}{}</li>",
                badge(test.passed),
                escape_html(&test.name),
                test.error
                    .as_ref()
                    .map(|error| format!(" <code>{}</code>", escape_html(error)))
                    .unwrap_or_default(),
            ));
        }
        rows.push_str(&format!(
            "<tr class=\"{row_class}\"><td>{row_badge}</td><td>{escaped_name}</td>\
             <td>{status}</td><td>{time_ms} ms</td><td>{passed}/{total} \
             <ul class=\"tests\">{test_items}</ul></td></tr>",
            row_class = status_class(result),
            row_badge = badge(result.tests.iter().all(|t| t.passed)),
            escaped_name = escape_html(&result.request_name),
            status = result.status,
            time_ms = result.time_ms,
            passed = passed,
            total = total,
            test_items = test_items,
        ));
    }

    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{name} — Run Report</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: system-ui, sans-serif; margin: 24px; background: #0f172a; color: #e2e8f0; }}
  h1 {{ margin-bottom: 4px; }}
  .meta {{ color: #94a3b8; font-size: 0.85rem; margin-bottom: 20px; }}
  .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin-bottom: 24px; }}
  .card {{ background: #1e293b; border-radius: 10px; padding: 14px 16px; }}
  .card .value {{ font-size: 1.6rem; font-weight: 700; }}
  .card .label {{ color: #94a3b8; font-size: 0.75rem; text-transform: uppercase; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid #334155; vertical-align: top; }}
  tr.pass td:first-child {{ border-left: 3px solid #22c55e; }}
  tr.fail td:first-child {{ border-left: 3px solid #ef4444; }}
  .badge {{ font-size: 0.7rem; font-weight: 700; padding: 2px 6px; border-radius: 4px; }}
  .badge.pass {{ background: rgba(34,197,94,.15); color: #22c55e; }}
  .badge.fail {{ background: rgba(239,68,68,.15); color: #ef4444; }}
  ul.tests {{ list-style: none; padding: 0; margin: 6px 0 0; }}
  code {{ color: #fca5a5; }}
</style>
</head>
<body>
<h1>{name} — Run Report</h1>
<p class="meta">Generated by Tyny Pulse · duration {duration} ms</p>
<div class="cards">
  <div class="card"><div class="value">{total}</div><div class="label">Requests</div></div>
  <div class="card"><div class="value">{passed_req}</div><div class="label">Passed requests</div></div>
  <div class="card"><div class="value">{failed_req}</div><div class="label">Failed requests</div></div>
  <div class="card"><div class="value">{passed_assertions}/{total_assertions}</div><div class="label">Assertions</div></div>
</div>
<table>
<thead><tr><th>Request</th><th>Status</th><th>Time</th><th>Tests</th></tr></thead>
<tbody>{rows}</tbody>
</table>
</body>
</html>
"#,
        name = name,
        duration = duration_ms,
        total = report.total_requests,
        passed_req = passed_requests,
        failed_req = failed_requests,
        passed_assertions = report.passed_tests,
        total_assertions = report.total_tests,
        rows = rows,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::models::TestResult;

    fn sample_report() -> CollectionRunReport {
        CollectionRunReport {
            total_requests: 2,
            total_tests: 3,
            passed_tests: 2,
            results: vec![
                RequestRunResult {
                    request_name: "health check".to_string(),
                    status: 200,
                    time_ms: 12,
                    tests: vec![TestResult {
                        name: "status is ok".to_string(),
                        passed: true,
                        error: None,
                    }],
                },
                RequestRunResult {
                    request_name: "create <user>".to_string(),
                    status: 500,
                    time_ms: 40,
                    tests: vec![
                        TestResult {
                            name: "created".to_string(),
                            passed: false,
                            error: Some("expected 201 <body>".to_string()),
                        },
                        TestResult {
                            name: "fast enough".to_string(),
                            passed: true,
                            error: None,
                        },
                    ],
                },
            ],
        }
    }

    #[test]
    fn renders_standalone_document_with_summary_and_rows() {
        let html = render_html("smoke", &sample_report(), 1420);

        assert!(html.starts_with("<!doctype html>"));
        assert!(html.contains("<title>smoke — Run Report</title>"));
        assert!(html.contains("duration 1420 ms"));
        assert!(html.contains("Requests</div></div>"));
        // Per-request rows carry pass/fail styling and the assertion ratio.
        assert!(html.contains(r#"class="pass""#));
        assert!(html.contains(r#"class="fail""#));
        assert!(html.contains("2/3"));
    }

    #[test]
    fn escapes_html_sensitive_characters_in_dynamic_content() {
        let html = render_html("smoke", &sample_report(), 10);

        assert!(html.contains("&lt;user&gt;"), "request names must be escaped");
        assert!(html.contains("expected 201 &lt;body&gt;"));
        assert!(!html.contains("<user>"));
    }

    #[test]
    fn zero_request_runs_render_an_empty_table_body() {
        let report = CollectionRunReport {
            total_requests: 0,
            total_tests: 0,
            passed_tests: 0,
            results: vec![],
        };
        let html = render_html("empty", &report, 1);

        assert!(html.contains("<tbody></tbody>"));
        assert!(html.contains("<div class=\"value\">0</div>"));
    }
}
