// src-tauri/src/infrastructure/reporting/markdown_reporter.rs
//
// Markdown rendering for collection runs — human-readable artifact for
// pull requests, issues and documentation.

use crate::domain::models::CollectionRunReport;

/// Renders a collection run as a GitHub-flavored Markdown document.
pub fn render_markdown(
    collection_name: &str,
    report: &CollectionRunReport,
    duration_ms: u64,
) -> String {
    let passed_requests = report
        .results
        .iter()
        .filter(|result| result.tests.iter().all(|test| test.passed))
        .count();

    let mut md = format!(
        "# Collection Run Report — {collection_name}\n\n\
         Generated by **Tyny Pulse** · duration {duration_ms} ms\n\n\
         ## Summary\n\n\
         | Metric | Value |\n| :--- | :--- |\n\
         | Requests | {} |\n\
         | Passed requests | {} |\n\
         | Failed requests | {} |\n\
         | Assertions | {}/{} passed |\n\n\
         ## Results\n\n",
        report.total_requests,
        passed_requests,
        report.total_requests - passed_requests,
        report.passed_tests,
        report.total_tests,
    );

    for result in &report.results {
        let all_passed = result.tests.iter().all(|test| test.passed);
        let marker = if all_passed { "✅" } else { "❌" };
        md.push_str(&format!(
            "### {} {} — {} ({} ms)\n\n",
            marker, result.request_name, result.status, result.time_ms
        ));
        if result.tests.is_empty() {
            md.push_str("_No assertions configured._\n\n");
            continue;
        }
        for test in &result.tests {
            let flag = if test.passed { "✅" } else { "❌" };
            match &test.error {
                Some(error) => md.push_str(&format!("- {flag} {} — `{}`\n", test.name, error)),
                None => md.push_str(&format!("- {flag} {}\n", test.name)),
            }
        }
        md.push('\n');
    }

    md
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::models::{RequestRunResult, TestResult};

    fn sample_report() -> CollectionRunReport {
        CollectionRunReport {
            total_requests: 1,
            total_tests: 2,
            passed_tests: 1,
            results: vec![RequestRunResult {
                request_name: "health check".to_string(),
                status: 200,
                time_ms: 9,
                tests: vec![
                    TestResult { name: "status ok".to_string(), passed: true, error: None },
                    TestResult {
                        name: "payload".to_string(),
                        passed: false,
                        error: Some("missing field".to_string()),
                    },
                ],
            }],
        }
    }

    #[test]
    fn renders_summary_and_per_test_markers() {
        let md = render_markdown("smoke", &sample_report(), 42);

        assert!(md.contains("# Collection Run Report — smoke"));
        assert!(md.contains("| Requests | 1 |"));
        // One failing assertion marks the whole request as failed.
        assert!(md.contains("### ❌ health check — 200 (9 ms)"));
        assert!(md.contains("- ✅ status ok"));
        assert!(md.contains("- ❌ payload — `missing field`"));
    }

    #[test]
    fn empty_runs_note_missing_assertions() {
        let mut report = sample_report();
        report.results[0].tests.clear();
        let md = render_markdown("smoke", &report, 1);
        assert!(md.contains("_No assertions configured._"));
    }
}
